// Posts
export const LOAD_POSTS_REQUEST = 'LOAD_POSTS_REQUEST'
export const LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS'
export const LOAD_POSTS_FAILURE = 'LOAD_POSTS_FAILURE'

// Single Post
export const LOAD_POST_REQUEST = 'LOAD_POST_REQUEST'
export const LOAD_POST_SUCCESS = 'LOAD_POST_SUCCESS'
export const LOAD_POST_FAILURE = 'LOAD_POST_FAILURE'

// Rebates
export const LOAD_REBATES_REQUEST = 'LOAD_REBATES_REQUEST'
export const LOAD_REBATES_SUCCESS = 'LOAD_REBATES_SUCCESS'
export const LOAD_REBATES_FAILURE = 'LOAD_REBATES_FAILURE'

// More Rebates
export const LOAD_MORE_REBATES_REQUEST = 'LOAD_MORE_REBATES_REQUEST'
export const LOAD_MORE_REBATES_SUCCESS = 'LOAD_MORE_REBATES_SUCCESS'
export const LOAD_MORE_REBATES_FAILURE = 'LOAD_MORE_REBATES_FAILURE'

// Single Rebate
export const LOAD_REBATE_REQUEST = 'LOAD_REBATE_REQUEST'
export const LOAD_REBATE_SUCCESS = 'LOAD_REBATE_SUCCESS'
export const LOAD_REBATE_FAILURE = 'LOAD_REBATE_FAILURE'
